name: Build Ruby 3.0.7 RPM with OpenSSL 1.1

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Target architecture'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - x86_64
          - aarch64

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - ${{ (github.event.inputs.architecture == 'both' || github.event.inputs.architecture == 'x86_64') && 'x86_64' || null }}
          - ${{ (github.event.inputs.architecture == 'both' || github.event.inputs.architecture == 'aarch64') && 'aarch64' || null }}
        exclude:
          - arch: null

    name: Build Ruby RPM (${{ matrix.arch }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build Ruby RPM Docker image
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            PLATFORM="linux/amd64"
            TAG_SUFFIX="x86"
          else
            PLATFORM="linux/arm64"
            TAG_SUFFIX="arm64"
          fi

          docker buildx build \
            --platform $PLATFORM \
            --load \
            -t ruby-builder-$TAG_SUFFIX \
            --build-arg TARGETARCH=${{ matrix.arch }} \
            .

      - name: Extract RPMs from container
        run: |
          mkdir -p output-${{ matrix.arch }}

          # Set correct tag suffix
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            TAG_SUFFIX="x86"
          else
            TAG_SUFFIX="arm64"
          fi

          # Run container and extract files using the correct tag
          docker run --rm -v $(pwd)/output-${{ matrix.arch }}:/output ruby-builder-$TAG_SUFFIX bash -c "
            # Check what's actually in the container
            echo 'Container contents:'
            ls -la /home/builder/
            echo 'RPM build output:'
            ls -la /home/builder/output/ 2>/dev/null || echo 'No output directory found'
            echo 'RPMS directory:'
            ls -la /home/builder/rpmbuild/RPMS/ 2>/dev/null || echo 'No RPMS directory found'

            # Copy from the container's output directory using find to avoid glob issues
            if [ -d '/home/builder/output' ]; then
              find /home/builder/output -name '*.rpm' -type f -exec cp {} /output/ \; 2>/dev/null
              if [ \$? -eq 0 ]; then
                echo 'Copied RPMs from output directory'
              else
                echo 'No RPMs in output directory'
              fi
            fi

            # Also try the traditional RPM build locations
            if [ -d '/home/builder/rpmbuild/RPMS' ]; then
              find /home/builder/rpmbuild/RPMS -name '*.rpm' -type f -exec cp {} /output/ \; 2>/dev/null
              if [ \$? -eq 0 ]; then
                echo 'Copied RPMs from rpmbuild'
              else
                echo 'No RPMs in rpmbuild'
              fi
            fi

            if [ -d '/home/builder/rpmbuild/SRPMS' ]; then
              find /home/builder/rpmbuild/SRPMS -name '*.rpm' -type f -exec cp {} /output/ \; 2>/dev/null
              if [ \$? -eq 0 ]; then
                echo 'Copied source RPMs'
              else
                echo 'No source RPMs found'
              fi
            fi

            # Copy spec files if they exist
            [ -f '/home/builder/rpmbuild/SPECS/ruby.spec' ] && cp /home/builder/rpmbuild/SPECS/ruby.spec /output/ruby-modified.spec && echo 'Copied modified spec' || echo 'No modified spec found'
            [ -f '/home/builder/rpmbuild/SPECS/ruby.spec.bak' ] && cp /home/builder/rpmbuild/SPECS/ruby.spec.bak /output/ruby-original.spec && echo 'Copied original spec' || echo 'No original spec found'

            echo 'Final output contents:'
            ls -la /output/
          "

      - name: List built RPMs
        run: |
          echo "Built RPMs for ${{ matrix.arch }}:"
          ls -la output-${{ matrix.arch }}/

          echo "RPM details:"
          for rpm in output-${{ matrix.arch }}/*.rpm; do
            if [ -f "$rpm" ]; then
              echo "=== $(basename $rpm) ==="
              rpm -qp --info "$rpm" 2>/dev/null || echo "Could not read RPM info"
            fi
          done

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ruby-3.0.7-rpms-${{ matrix.arch }}
          path: |
            output-${{ matrix.arch }}/*.rpm
            output-${{ matrix.arch }}/*.spec
          retention-days: 30

  summary:
    needs: build-rpm
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Create build summary
        run: |
          echo "# Ruby 3.0.7 RPM Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Built Packages" >> $GITHUB_STEP_SUMMARY

          for arch_dir in all-artifacts/ruby-3.0.7-rpms-*; do
            if [ -d "$arch_dir" ]; then
              arch=$(basename "$arch_dir" | sed 's/ruby-3.0.7-rpms-//')
              echo "### $arch Architecture" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              ls -la "$arch_dir"/ >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            fi
          done

          echo "## Key Features" >> $GITHUB_STEP_SUMMARY
          echo "- Ruby 3.0.7 compiled with OpenSSL 1.1.1w support" >> $GITHUB_STEP_SUMMARY
          echo "- Compatible with Amazon Linux 2023" >> $GITHUB_STEP_SUMMARY
          echo "- Includes all standard Ruby gems and libraries" >> $GITHUB_STEP_SUMMARY
          echo "- Debug packages available for troubleshooting" >> $GITHUB_STEP_SUMMARY

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ruby-3.0.7-all-rpms
          path: all-artifacts/
          retention-days: 30